name: shortlink

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      provenance: false
      sbom: false
    image: shortlink:latest
    container_name: shortlink
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "${APP_PORT:-80}:80"
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      SERVER_PORT: 8080
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
